apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  mysql-root-password: dGVzdHJvb3Q=
  mysql-user: dGVzdA==
  mysql-password: dGVzdG5vdw==
  mysql-database: bXlzcWw=